// cypress/e2e/story-002-user-registration.cy.ts
// Generated by Agentic Testing Workflow
// Story: User Registration Flow

describe('Story-002: User Registration Flow', () => {
  // ===========================================================================
  // TEST DATA
  // ===========================================================================

  const validUser = {
    fullName: 'Test User',
    email: `test.user.${Date.now()}@example.com`, // Unique email per run
    password: 'SecurePass123!',
  };

  const existingUser = {
    email: 'existing@example.com',
    password: 'ExistingPass123!',
  };

  const invalidEmails = [
    'notanemail',
    'missing@domain',
    '@nodomain.com',
    'spaces in@email.com',
  ];

  const weakPasswords = [
    { value: 'Short1!', error: 'at least 8 characters' },
    { value: 'lowercase123!', error: 'uppercase letter' },
    { value: 'UPPERCASE123!', error: 'lowercase letter' },
    { value: 'NoNumbers!!', error: 'number' },
    { value: 'NoSpecial123', error: 'special character' },
  ];

  // ===========================================================================
  // SETUP & HELPERS
  // ===========================================================================

  beforeEach(() => {
    // Reset any previous state
    cy.clearCookies();
    cy.clearLocalStorage();
    
    // Visit registration page
    cy.visit('/register');
    
    // Wait for page to load
    cy.get('[data-testid="registration-form"]').should('be.visible');
  });

  /**
   * Helper: Fill registration form
   */
  const fillRegistrationForm = (data: Partial<typeof validUser & { confirmPassword: string }>) => {
    if (data.fullName) {
      cy.get('[data-testid="fullName-input"]').clear().type(data.fullName);
    }
    if (data.email) {
      cy.get('[data-testid="email-input"]').clear().type(data.email);
    }
    if (data.password) {
      cy.get('[data-testid="password-input"]').clear().type(data.password);
    }
    if (data.confirmPassword) {
      cy.get('[data-testid="confirm-password-input"]').clear().type(data.confirmPassword);
    }
  };

  /**
   * Helper: Accept terms of service
   */
  const acceptTerms = () => {
    cy.get('[data-testid="terms-checkbox"]').check();
  };

  /**
   * Helper: Submit registration form
   */
  const submitForm = () => {
    cy.get('[data-testid="register-button"]').click();
  };

  // ===========================================================================
  // SMOKE TESTS - Critical Path
  // ===========================================================================

  describe('Smoke Tests', () => {
    it('@smoke @happy-path should complete registration with valid data', () => {
      // Fill form with valid data
      fillRegistrationForm({
        fullName: validUser.fullName,
        email: validUser.email,
        password: validUser.password,
        confirmPassword: validUser.password,
      });
      
      // Accept terms
      acceptTerms();
      
      // Submit form
      submitForm();
      
      // Verify success
      cy.get('[data-testid="success-message"]').should('be.visible');
      cy.url().should('include', '/verify-email');
      
      // TODO: Verify confirmation email was sent (requires email interceptor)
      // cy.task('getLastEmail', validUser.email).should('contain', 'verification');
    });

    it('@smoke @navigation should navigate to registration from login page', () => {
      cy.visit('/login');
      cy.get('[data-testid="signup-link"]').click();
      cy.url().should('include', '/register');
      cy.get('[data-testid="registration-form"]').should('be.visible');
    });

    it('@smoke @ui should display all required form fields', () => {
      // Verify all fields are present
      cy.get('[data-testid="fullName-input"]').should('be.visible');
      cy.get('[data-testid="email-input"]').should('be.visible');
      cy.get('[data-testid="password-input"]').should('be.visible');
      cy.get('[data-testid="confirm-password-input"]').should('be.visible');
      cy.get('[data-testid="terms-checkbox"]').should('be.visible');
      
      // Verify password requirements are displayed
      cy.get('[data-testid="password-requirements"]').should('be.visible');
    });
  });

  // ===========================================================================
  // VALIDATION TESTS - Email
  // ===========================================================================

  describe('Email Validation', () => {
    invalidEmails.forEach((invalidEmail) => {
      it(`@regression @validation should show error for invalid email: ${invalidEmail}`, () => {
        cy.get('[data-testid="email-input"]').type(invalidEmail);
        cy.get('[data-testid="email-input"]').blur();
        
        cy.get('[data-testid="email-error"]').should('be.visible');
        cy.get('[data-testid="register-button"]').should('be.disabled');
      });
    });

    it('@regression @validation should accept valid email format', () => {
      cy.get('[data-testid="email-input"]').type('valid.email@example.com');
      cy.get('[data-testid="email-input"]').blur();
      
      cy.get('[data-testid="email-error"]').should('not.exist');
    });
  });

  // ===========================================================================
  // VALIDATION TESTS - Password Requirements
  // ===========================================================================

  describe('Password Validation', () => {
    weakPasswords.forEach(({ value, error }) => {
      it(`@regression @validation should show error for password: ${value}`, () => {
        cy.get('[data-testid="password-input"]').type(value);
        cy.get('[data-testid="password-input"]').blur();
        
        cy.get('[data-testid="password-error"]')
          .should('be.visible')
          .and('contain', error);
      });
    });

    it('@regression @validation should show error when passwords do not match', () => {
      cy.get('[data-testid="password-input"]').type('SecurePass123!');
      cy.get('[data-testid="confirm-password-input"]').type('DifferentPass123!');
      cy.get('[data-testid="confirm-password-input"]').blur();
      
      cy.get('[data-testid="confirm-password-error"]')
        .should('be.visible')
        .and('contain', 'match');
    });

    it('@regression @ux should update password requirements in real-time', () => {
      const passwordInput = cy.get('[data-testid="password-input"]');
      
      // Start with partial password
      passwordInput.type('secure');
      cy.get('[data-testid="req-length"]').should('not.have.class', 'satisfied');
      cy.get('[data-testid="req-uppercase"]').should('not.have.class', 'satisfied');
      
      // Add uppercase
      passwordInput.clear().type('Secure');
      cy.get('[data-testid="req-uppercase"]').should('have.class', 'satisfied');
      
      // Complete the password
      passwordInput.clear().type('SecurePass123!');
      cy.get('[data-testid="req-length"]').should('have.class', 'satisfied');
      cy.get('[data-testid="req-uppercase"]').should('have.class', 'satisfied');
      cy.get('[data-testid="req-lowercase"]').should('have.class', 'satisfied');
      cy.get('[data-testid="req-number"]').should('have.class', 'satisfied');
      cy.get('[data-testid="req-special"]').should('have.class', 'satisfied');
    });
  });

  // ===========================================================================
  // VALIDATION TESTS - Required Fields
  // ===========================================================================

  describe('Required Field Validation', () => {
    it('@regression @validation should show errors for empty form submission', () => {
      submitForm();
      
      cy.get('[data-testid="fullName-error"]').should('be.visible');
      cy.get('[data-testid="email-error"]').should('be.visible');
      cy.get('[data-testid="password-error"]').should('be.visible');
      cy.get('[data-testid="confirm-password-error"]').should('be.visible');
      cy.get('[data-testid="terms-error"]').should('be.visible');
    });

    it('@regression @validation should require terms acceptance', () => {
      fillRegistrationForm({
        fullName: validUser.fullName,
        email: validUser.email,
        password: validUser.password,
        confirmPassword: validUser.password,
      });
      
      // Don't accept terms
      submitForm();
      
      cy.get('[data-testid="terms-error"]')
        .should('be.visible')
        .and('contain', 'accept the terms');
    });
  });

  // ===========================================================================
  // ERROR HANDLING - Duplicate Email
  // ===========================================================================

  describe('Duplicate Email Handling', () => {
    it('@regression @error @security should show error for duplicate email without leaking info', () => {
      // Use the pre-existing user email
      fillRegistrationForm({
        fullName: 'Another User',
        email: existingUser.email,
        password: validUser.password,
        confirmPassword: validUser.password,
      });
      acceptTerms();
      submitForm();
      
      // Verify error message is shown but doesn't reveal account exists
      cy.get('[data-testid="form-error"]')
        .should('be.visible')
        .and('not.contain', 'already exists')
        .and('not.contain', 'account found');
    });
  });

  // ===========================================================================
  // SECURITY TESTS
  // ===========================================================================

  describe('Security Tests', () => {
    it('@smoke @security should mask password input', () => {
      cy.get('[data-testid="password-input"]')
        .should('have.attr', 'type', 'password');
      
      cy.get('[data-testid="confirm-password-input"]')
        .should('have.attr', 'type', 'password');
    });

    it('@regression @security should sanitize XSS payloads in form fields', () => {
      const xssPayload = '<script>alert("xss")</script>';
      
      fillRegistrationForm({
        fullName: xssPayload,
        email: 'xss.test@example.com',
        password: validUser.password,
        confirmPassword: validUser.password,
      });
      acceptTerms();
      submitForm();
      
      // If registration succeeds, verify the script didn't execute
      cy.window().then((win) => {
        // Script should not have executed
        cy.wrap(win.document.body.innerHTML).should('not.contain', '<script>');
      });
    });

    it('@regression @security should include CSRF token in form', () => {
      cy.get('[data-testid="registration-form"]').within(() => {
        cy.get('input[name="_csrf"]').should('exist');
      });
    });
  });

  // ===========================================================================
  // API TESTS
  // ===========================================================================

  describe('API Tests', () => {
    it('@api @smoke should return 201 on successful registration', () => {
      const apiUser = {
        fullName: 'API Test User',
        email: `api.test.${Date.now()}@example.com`,
        password: 'SecurePass123!',
      };

      cy.request({
        method: 'POST',
        url: '/api/auth/register',
        body: apiUser,
      }).then((response) => {
        expect(response.status).to.eq(201);
        expect(response.body).to.have.property('userId');
        expect(response.body).to.not.have.property('password');
      });
    });

    it('@api @validation should return 400 for invalid email', () => {
      cy.request({
        method: 'POST',
        url: '/api/auth/register',
        body: {
          fullName: 'Test User',
          email: 'invalid-email',
          password: 'SecurePass123!',
        },
        failOnStatusCode: false,
      }).then((response) => {
        expect(response.status).to.eq(400);
        expect(response.body.error).to.contain('email');
      });
    });

    it('@api @validation should return 400 for weak password', () => {
      cy.request({
        method: 'POST',
        url: '/api/auth/register',
        body: {
          fullName: 'Test User',
          email: 'test@example.com',
          password: 'weak',
        },
        failOnStatusCode: false,
      }).then((response) => {
        expect(response.status).to.eq(400);
        expect(response.body.error).to.contain('password');
      });
    });

    it('@api @error should return 409 for duplicate email', () => {
      cy.request({
        method: 'POST',
        url: '/api/auth/register',
        body: {
          fullName: 'Duplicate User',
          email: existingUser.email,
          password: 'SecurePass123!',
        },
        failOnStatusCode: false,
      }).then((response) => {
        expect(response.status).to.eq(409);
      });
    });

    it('@api @security should enforce rate limiting', () => {
      const email = 'ratelimit@example.com';
      
      // Make 6 requests (limit is 5)
      const requests = Array(6).fill(null).map((_, i) => 
        cy.request({
          method: 'POST',
          url: '/api/auth/register',
          body: {
            fullName: 'Rate Limit Test',
            email: `${i}-${email}`,
            password: 'SecurePass123!',
          },
          failOnStatusCode: false,
        })
      );

      // The 6th request should be rate limited
      cy.wrap(requests[5]).then((response: any) => {
        expect(response.status).to.eq(429);
      });
    });
  });

  // ===========================================================================
  // EMAIL VERIFICATION INTEGRATION
  // ===========================================================================

  describe('Email Verification Integration', () => {
    it('@integration @email should prevent login before verification', () => {
      // Register new user
      const unverifiedEmail = `unverified.${Date.now()}@example.com`;
      
      cy.request({
        method: 'POST',
        url: '/api/auth/register',
        body: {
          fullName: 'Unverified User',
          email: unverifiedEmail,
          password: validUser.password,
        },
      });

      // Attempt to login
      cy.visit('/login');
      cy.get('[data-testid="email-input"]').type(unverifiedEmail);
      cy.get('[data-testid="password-input"]').type(validUser.password);
      cy.get('[data-testid="login-button"]').click();

      // Should show verification required message
      cy.get('[data-testid="error-message"]')
        .should('be.visible')
        .and('contain', 'verify');
    });

    // TODO: Test email verification flow
    // This requires email interception/mocking setup
    // it('@integration @email should allow login after verification', () => {
    //   // 1. Register user
    //   // 2. Get verification email via cy.task
    //   // 3. Extract and visit verification link
    //   // 4. Attempt login - should succeed
    // });
  });
});
