// cypress/e2e/story-001-delete-user.cy.ts
// Generated by Agentic Testing Workflow
// Story: Delete a User

describe('Story-001: Delete User', () => {
  // ===========================================================================
  // TEST DATA
  // ===========================================================================

  const adminUser = {
    id: 'admin-001',
    email: 'admin@example.com',
    password: 'AdminPass123!',
    role: 'admin',
  };

  const regularUser = {
    id: 'user-001',
    email: 'user@example.com',
    password: 'UserPass123!',
    role: 'user',
  };

  const userToDelete = {
    id: 'delete-001',
    email: 'deleteme@example.com',
    password: 'DeleteMe123!',
    role: 'user',
  };

  // ===========================================================================
  // SETUP & HELPERS
  // ===========================================================================

  beforeEach(() => {
    // Reset database state
    cy.task('db:reset');
    
    // Seed test users
    cy.task('db:seed', {
      users: [adminUser, regularUser, userToDelete],
    });
  });

  /**
   * Helper: Login as a specific user
   */
  const loginAs = (user: typeof adminUser) => {
    cy.session(user.email, () => {
      cy.visit('/login');
      cy.get('[data-testid="email-input"]').type(user.email);
      cy.get('[data-testid="password-input"]').type(user.password);
      cy.get('[data-testid="login-button"]').click();
      cy.url().should('not.include', '/login');
    });
  };

  /**
   * Helper: Get admin auth token for API calls
   */
  const getAdminToken = () => {
    return cy.request({
      method: 'POST',
      url: '/api/auth/login',
      body: {
        email: adminUser.email,
        password: adminUser.password,
      },
    }).then((res) => res.body.token);
  };

  /**
   * Helper: Get regular user token for API calls
   */
  const getUserToken = () => {
    return cy.request({
      method: 'POST',
      url: '/api/auth/login',
      body: {
        email: regularUser.email,
        password: regularUser.password,
      },
    }).then((res) => res.body.token);
  };

  // ===========================================================================
  // SMOKE TESTS - Critical Path
  // ===========================================================================

  describe('Smoke Tests', () => {
    it('@smoke @happy-path Admin successfully deletes a user via UI', () => {
      loginAs(adminUser);
      cy.visit('/admin/users');

      // Find and click delete button for target user
      cy.contains('tr', userToDelete.email)
        .find('[data-testid="delete-button"]')
        .click();

      // Confirm deletion in dialog
      cy.get('[data-testid="confirm-dialog"]').should('be.visible');
      cy.get('[data-testid="confirm-delete-button"]').click();

      // Verify success
      cy.get('[data-testid="success-toast"]')
        .should('be.visible')
        .and('contain', 'deleted');

      // Verify user removed from table
      cy.contains('tr', userToDelete.email).should('not.exist');

      // Verify audit entry created (via API)
      getAdminToken().then((token) => {
        cy.request({
          method: 'GET',
          url: '/api/audit/logs',
          headers: { Authorization: `Bearer ${token}` },
          qs: { action: 'user.delete', targetId: userToDelete.id },
        }).then((res) => {
          expect(res.body.logs).to.have.length.at.least(1);
          expect(res.body.logs[0].actorId).to.eq(adminUser.id);
        });
      });
    });

    it('@smoke @security Non-admin user cannot see delete button', () => {
      loginAs(regularUser);
      cy.visit('/admin/users');

      // Should either redirect or not show delete buttons
      cy.get('[data-testid="delete-button"]').should('not.exist');
    });

    it('@smoke Deleted user is removed from users table', () => {
      loginAs(adminUser);
      
      // Delete user via API first
      getAdminToken().then((token) => {
        cy.request({
          method: 'DELETE',
          url: `/api/users/${userToDelete.id}`,
          headers: { Authorization: `Bearer ${token}` },
        });
      });

      // Verify not in UI
      cy.visit('/admin/users');
      cy.contains('tr', userToDelete.email).should('not.exist');
    });
  });

  // ===========================================================================
  // AUTHORIZATION TESTS
  // ===========================================================================

  describe('Authorization Tests', () => {
    it('@regression @security Non-admin receives 403 when attempting delete via API', () => {
      getUserToken().then((token) => {
        cy.request({
          method: 'DELETE',
          url: `/api/users/${userToDelete.id}`,
          headers: { Authorization: `Bearer ${token}` },
          failOnStatusCode: false,
        }).then((res) => {
          expect(res.status).to.eq(403);
          expect(res.body.error).to.contain('permission');
        });
      });

      // Verify user still exists
      getAdminToken().then((token) => {
        cy.request({
          method: 'GET',
          url: `/api/users/${userToDelete.id}`,
          headers: { Authorization: `Bearer ${token}` },
        }).then((res) => {
          expect(res.status).to.eq(200);
        });
      });
    });

    it('@regression @security Unauthenticated request returns 401', () => {
      cy.request({
        method: 'DELETE',
        url: `/api/users/${userToDelete.id}`,
        failOnStatusCode: false,
      }).then((res) => {
        expect(res.status).to.eq(401);
      });
    });
  });

  // ===========================================================================
  // UI BEHAVIOR TESTS
  // ===========================================================================

  describe('UI Behavior', () => {
    it('@regression @ui Delete confirmation dialog appears', () => {
      loginAs(adminUser);
      cy.visit('/admin/users');

      cy.contains('tr', userToDelete.email)
        .find('[data-testid="delete-button"]')
        .click();

      cy.get('[data-testid="confirm-dialog"]').should('be.visible');
      cy.get('[data-testid="confirm-dialog"]').should('contain', userToDelete.email);
      cy.get('[data-testid="cancel-button"]').should('be.visible');
      cy.get('[data-testid="confirm-delete-button"]').should('be.visible');
    });

    it('@regression @ui Cancel delete returns to user list without changes', () => {
      loginAs(adminUser);
      cy.visit('/admin/users');

      cy.contains('tr', userToDelete.email)
        .find('[data-testid="delete-button"]')
        .click();

      cy.get('[data-testid="cancel-button"]').click();

      cy.get('[data-testid="confirm-dialog"]').should('not.exist');
      cy.contains('tr', userToDelete.email).should('exist');
    });

    it('@regression @ui Success toast shown after deletion', () => {
      loginAs(adminUser);
      cy.visit('/admin/users');

      cy.contains('tr', userToDelete.email)
        .find('[data-testid="delete-button"]')
        .click();

      cy.get('[data-testid="confirm-delete-button"]').click();

      cy.get('[data-testid="success-toast"]')
        .should('be.visible')
        .and('contain', 'deleted');

      // Toast should auto-dismiss
      cy.get('[data-testid="success-toast"]', { timeout: 10000 }).should('not.exist');
    });

    it('@regression @error Error toast shown when deletion fails', () => {
      // Intercept delete request and force failure
      cy.intercept('DELETE', `/api/users/${userToDelete.id}`, {
        statusCode: 500,
        body: { error: 'Internal server error' },
      });

      loginAs(adminUser);
      cy.visit('/admin/users');

      cy.contains('tr', userToDelete.email)
        .find('[data-testid="delete-button"]')
        .click();

      cy.get('[data-testid="confirm-delete-button"]').click();

      cy.get('[data-testid="error-toast"]').should('be.visible');
      cy.contains('tr', userToDelete.email).should('exist');
    });
  });

  // ===========================================================================
  // API TESTS
  // ===========================================================================

  describe('API Tests', () => {
    it('@api @smoke DELETE /users/:id returns 204 for admin', () => {
      getAdminToken().then((token) => {
        cy.request({
          method: 'DELETE',
          url: `/api/users/${userToDelete.id}`,
          headers: { Authorization: `Bearer ${token}` },
        }).then((res) => {
          expect(res.status).to.eq(204);
          expect(res.body).to.be.empty;
        });
      });
    });

    it('@api @security DELETE /users/:id returns 403 for non-admin', () => {
      getUserToken().then((token) => {
        cy.request({
          method: 'DELETE',
          url: `/api/users/${userToDelete.id}`,
          headers: { Authorization: `Bearer ${token}` },
          failOnStatusCode: false,
        }).then((res) => {
          expect(res.status).to.eq(403);
        });
      });
    });

    it('@api @error DELETE /users/:id returns 404 for non-existent user', () => {
      getAdminToken().then((token) => {
        cy.request({
          method: 'DELETE',
          url: '/api/users/non-existent-id',
          headers: { Authorization: `Bearer ${token}` },
          failOnStatusCode: false,
        }).then((res) => {
          expect(res.status).to.eq(404);
          expect(res.body.error).to.contain('not found');
        });
      });
    });

    it('@api @smoke GET /users excludes deleted user', () => {
      getAdminToken().then((token) => {
        // Delete the user
        cy.request({
          method: 'DELETE',
          url: `/api/users/${userToDelete.id}`,
          headers: { Authorization: `Bearer ${token}` },
        });

        // Verify not in list
        cy.request({
          method: 'GET',
          url: '/api/users',
          headers: { Authorization: `Bearer ${token}` },
        }).then((res) => {
          const userIds = res.body.users.map((u: any) => u.id);
          expect(userIds).to.not.include(userToDelete.id);
        });
      });
    });

    it('@api @security Deleted user cannot authenticate', () => {
      // Delete the user first
      getAdminToken().then((token) => {
        cy.request({
          method: 'DELETE',
          url: `/api/users/${userToDelete.id}`,
          headers: { Authorization: `Bearer ${token}` },
        });
      });

      // Attempt login
      cy.request({
        method: 'POST',
        url: '/api/auth/login',
        body: {
          email: userToDelete.email,
          password: userToDelete.password,
        },
        failOnStatusCode: false,
      }).then((res) => {
        expect(res.status).to.eq(401);
      });
    });
  });

  // ===========================================================================
  // AUDIT TESTS
  // ===========================================================================

  describe('Audit Tests', () => {
    it('@audit @compliance Audit entry created with correct data', () => {
      getAdminToken().then((token) => {
        // Delete user
        cy.request({
          method: 'DELETE',
          url: `/api/users/${userToDelete.id}`,
          headers: { Authorization: `Bearer ${token}` },
        });

        // Check audit log
        cy.request({
          method: 'GET',
          url: '/api/audit/logs',
          headers: { Authorization: `Bearer ${token}` },
          qs: { action: 'user.delete' },
        }).then((res) => {
          const log = res.body.logs.find(
            (l: any) => l.targetId === userToDelete.id
          );
          expect(log).to.exist;
          expect(log.actorId).to.eq(adminUser.id);
          expect(log.action).to.eq('user.delete');
          expect(log.timestamp).to.be.a('string');
        });
      });
    });

    it('@audit Failed deletion does not create audit entry', () => {
      getAdminToken().then((token) => {
        // Attempt to delete non-existent user
        cy.request({
          method: 'DELETE',
          url: '/api/users/non-existent-id',
          headers: { Authorization: `Bearer ${token}` },
          failOnStatusCode: false,
        });

        // Check no audit entry
        cy.request({
          method: 'GET',
          url: '/api/audit/logs',
          headers: { Authorization: `Bearer ${token}` },
          qs: { targetId: 'non-existent-id' },
        }).then((res) => {
          expect(res.body.logs).to.have.length(0);
        });
      });
    });
  });

  // ===========================================================================
  // EDGE CASE TESTS
  // ===========================================================================

  describe('Edge Cases', () => {
    it('@regression @edge-case Admin cannot delete themselves', () => {
      getAdminToken().then((token) => {
        cy.request({
          method: 'DELETE',
          url: `/api/users/${adminUser.id}`,
          headers: { Authorization: `Bearer ${token}` },
          failOnStatusCode: false,
        }).then((res) => {
          expect(res.status).to.be.oneOf([400, 403]);
          expect(res.body.error).to.contain('own account');
        });
      });
    });

    it('@regression @edge-case Deleting already-deleted user returns 404', () => {
      getAdminToken().then((token) => {
        // Delete once
        cy.request({
          method: 'DELETE',
          url: `/api/users/${userToDelete.id}`,
          headers: { Authorization: `Bearer ${token}` },
        });

        // Try to delete again
        cy.request({
          method: 'DELETE',
          url: `/api/users/${userToDelete.id}`,
          headers: { Authorization: `Bearer ${token}` },
          failOnStatusCode: false,
        }).then((res) => {
          expect(res.status).to.eq(404);
        });
      });
    });
  });
});
