/**
 * Base Prompt Module
 *
 * Shared prompt rules, formatting, and utilities used across all agents.
 * This provides the foundation for consistent, maintainable prompts.
 */

import { SystemContext } from '../types.js';

// ============================================================================
// PROMPT METADATA
// ============================================================================

export interface PromptMetadata {
  version: string;
  name: string;
  description: string;
  lastUpdated: string;
}

export interface BuiltPrompt {
  system: string;
  user: string;
  metadata: PromptMetadata;
}

// ============================================================================
// SHARED RULES
// ============================================================================

/**
 * Core rules that apply to ALL agents
 */
export const SHARED_RULES = {
  noHallucination: `- Do NOT make up information. If unsure, mark with TODO or ask for clarification.`,

  markUnknowns: `- Mark unknowns clearly with TODO comments rather than guessing.`,

  consistentFormat: `- Follow the output format specified. Do not deviate from the structure.`,

  noExtraContent: `- Do not include explanations outside the requested format unless explicitly asked.`,

  practicalFocus: `- Focus on practical, high-value outputs that solve real problems.`,
};

/**
 * Get shared rules as formatted string
 */
export function getSharedRules(rules: (keyof typeof SHARED_RULES)[]): string {
  return rules.map(key => SHARED_RULES[key]).join('\n');
}

// ============================================================================
// CONTEXT FORMATTING
// ============================================================================

/**
 * Format SystemContext for inclusion in prompts
 */
export function formatContext(context: SystemContext): string {
  const parts = [
    '## Tech Stack',
    `- Backend: ${context.techStack.backend}`,
    `- Frontend: ${context.techStack.frontend}`,
    `- Test Framework: ${context.techStack.testFramework}`,
    `- Language: ${context.techStack.language}`,
    '',
    '## Testing Principles',
    ...context.testingPrinciples.map(p => `- ${p}`),
  ];

  if (context.domainConstraints.length > 0) {
    parts.push('', '## Domain Constraints');
    for (const c of context.domainConstraints) {
      parts.push(`### ${c.entity}`);
      parts.push(...c.rules.map(r => `- ${r}`));
    }
  }

  return parts.join('\n');
}

// ============================================================================
// PROMPT ARTIFACT GENERATION
// ============================================================================

/**
 * Generate a prompt artifact for persistence
 * This is saved alongside generated artifacts for reproducibility
 */
export function generatePromptArtifact(prompt: BuiltPrompt): string {
  return `# Prompt Artifact

**Agent:** ${prompt.metadata.name}
**Version:** ${prompt.metadata.version}
**Generated:** ${new Date().toISOString()}

---

## System Prompt

\`\`\`
${prompt.system}
\`\`\`

## User Prompt

\`\`\`
${prompt.user}
\`\`\`

---

*This prompt artifact was saved for reproducibility and debugging.*
`;
}

// ============================================================================
// VERSION HEADER
// ============================================================================

/**
 * Add version comment to generated output
 */
export function addVersionHeader(
  content: string,
  metadata: PromptMetadata,
  format: 'markdown' | 'gherkin' | 'typescript'
): string {
  const timestamp = new Date().toISOString();

  switch (format) {
    case 'markdown':
      return `<!-- Generated by ${metadata.name} v${metadata.version} at ${timestamp} -->\n\n${content}`;
    case 'gherkin':
      return `# Generated by ${metadata.name} v${metadata.version} at ${timestamp}\n\n${content}`;
    case 'typescript':
      return `// Generated by ${metadata.name} v${metadata.version} at ${timestamp}\n\n${content}`;
    default:
      return content;
  }
}
