/**
 * Case Worker Agent Prompts
 *
 * Prompt module for the Case Worker agent that generates Gherkin scenarios.
 */

import { SystemContext, CaseWorkerPayload } from '../types.js';
import {
  PromptMetadata,
  BuiltPrompt,
  formatContext,
  getSharedRules,
} from './base.js';

// ============================================================================
// METADATA
// ============================================================================

export const CASES_PROMPT_METADATA: PromptMetadata = {
  version: '1.0.0',
  name: 'CaseWorkerAgent',
  description: 'Generates Gherkin test scenarios from test plans',
  lastUpdated: '2025-01-03',
};

// ============================================================================
// SYSTEM PROMPT
// ============================================================================

function buildSystemPrompt(context: SystemContext): string {
  return `You are a test case writer converting test plans into Gherkin scenarios.

${formatContext(context)}

## Your Task

Convert the test plan into valid Gherkin scenarios. Follow these rules:

1. **Output ONLY valid Gherkin** - no markdown, no explanations
2. **Start with a Feature block** that names the story
3. **Use appropriate tags**:
   - @story-XXX for the story ID
   - @smoke for critical happy path tests
   - @regression for edge cases and negative tests
   - @e2e for end-to-end scenarios
   - @api for API-focused tests
   - @security for security-related tests
4. **Keep steps high-level but concrete** - stable enough to not break with minor UI changes
5. **Reuse Given/When/Then phrasing** where similar scenarios exist
6. **Group scenarios logically** - happy path first, then negative, then edge cases

## Gherkin Format Example

Feature: Story ID - Feature Name

  Background:
    Given common preconditions

  @story-001 @smoke @e2e
  Scenario: Happy path description
    Given the precondition is met
    When the user performs the action
    Then the expected result occurs

  @story-001 @regression
  Scenario: Error handling scenario
    Given an error condition exists
    When the user attempts the action
    Then an appropriate error is shown

## Rules

${getSharedRules(['noHallucination', 'consistentFormat', 'noExtraContent'])}`;
}

// ============================================================================
// USER PROMPT
// ============================================================================

function buildUserPrompt(payload: CaseWorkerPayload): string {
  return `Convert the following test plan into Gherkin scenarios.

## Story: ${payload.storyId}

${payload.story}

## Test Plan

${payload.testPlan}

---

Generate valid Gherkin scenarios. Output ONLY the Gherkin - no markdown formatting, no explanations.`;
}

// ============================================================================
// PUBLIC API
// ============================================================================

/**
 * Build the complete prompt for the Case Worker agent
 */
export function buildCasesPrompt(
  context: SystemContext,
  payload: CaseWorkerPayload
): BuiltPrompt {
  return {
    system: buildSystemPrompt(context),
    user: buildUserPrompt(payload),
    metadata: CASES_PROMPT_METADATA,
  };
}

/**
 * Process raw LLM response into final Gherkin output
 */
export function processCasesResponse(response: string, storyId: string): string {
  // Clean up any markdown formatting that might have slipped in
  let cleaned = response
    .replace(/```gherkin\n?/g, '')
    .replace(/```\n?/g, '')
    .trim();

  // Ensure Feature line exists
  if (!cleaned.startsWith('Feature:')) {
    cleaned = `Feature: ${storyId} - Generated Test Scenarios\n\n${cleaned}`;
  }

  // Add version comment at top
  const header = `# Generated by ${CASES_PROMPT_METADATA.name} v${CASES_PROMPT_METADATA.version}`;
  if (!cleaned.startsWith('#')) {
    cleaned = `${header}\n\n${cleaned}`;
  }

  return cleaned;
}
